<a href="https://colab.research.google.com/github/ErickMM98/network_clustering_parallel/blob/main/foo_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

/usr/local/lib/python3.7/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-10.0/nvvm/libdevice
/usr/local/cuda-11.0/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/libdevice
/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so
/usr/local/cuda-11.0/nvvm/lib64/libnvvm.so
/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so


In [ ]:
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.1/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so"

In [ ]:
from numba import cuda
import numba
print(cuda.gpus)

<Managed Device 0>


In [ ]:
import random
# biblioteca de Numba
from numba import jit

#¡¡¡descomentar para optimizar, te vas a sorprender!!!
@jit(nopython=True)
def get_clustering(D):
  #t_diag = np.diag(D**3)
  #degree_vector = np.matrix([D[i][0].sum() for i in range(n) ])
  #degree_vector_minus_one = degree_vector - 1
  #divisor = np.array(degree_vector) * np.array(degree_vector_minus_one)
  print(np.diag(np.linalg.matrix_power(D, 3)) )#/ divisor)

# t_diag = np.diag(D**3)
# degree_vector = np.matrix([D[i][0].sum() for i in range(n) ])
# degree_vector_minus_one = degree_vector - 1
# divisor = np.array(degree_vector) * np.array(degree_vector_minus_one)
# print(t_diag / divisor)

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
import time 
import matplotlib.pyplot as plt
#G=nx.karate_club_graph()

G = nx.Graph()

G.add_edges_from([(1,2),
                  (2,3),
                  (3,4),
                  (4,5),
                  (5,2),
                  (4,2)])
n_g = 15
p = 0.5
G = nx.generators.random_graphs.binomial_graph(n_g, p)
n = G.number_of_nodes()

D = nx.adjacency_matrix(G)
D = D.toarray()
D = np.matrix(D) 
D = np.array(D)
print(D**3)
t_i = time.time()
get_clustering(D)
t_f = time.time()
t_m = t_f - t_i

print(t_m)
#print(degree_vector_minus_one)
#print(G.adj.items() )


#nodes_nbrs = ((n, G[n]) for n in G.nbunch_iter(nodes))
nodes_nbrs = G.adj.items()

t_i = time.time()
#list_foo = []
#print(nx.clustering(G))
"""
for v, v_nbrs in nodes_nbrs:
    #print(v,v_nbrs)
    vs = set(v_nbrs) - {v}
    #print(vs)
    #print(set(G[v]))
    gen_degree = Counter(len(vs & (set(G[w]) - {w})) for w in vs)
    #print(gen_degree)
    ntriangles = sum(k * val for k, val in gen_degree.items())
    list_foo.append(ntriangles)
    #print(ntriangles)
    #yield (v, len(vs), ntriangles, gen_degree)
"""    
t_f = time.time()
t_m = t_f - t_i
#print(list_foo)
print(t_m)

# Pruebas

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
import time 
import matplotlib.pyplot as plt


n_g = 15
p = 0.5
G = nx.generators.random_graphs.binomial_graph(n_g, p)
n = G.number_of_nodes()

D = nx.adjacency_matrix(G)
D = D.toarray()
D = np.matrix(D) 
D = np.array(D)
#print(D**3
t_i = time.time()
#get_clustering(D)
print(np.linalg.matrix_power(D,3))
t_f = time.time()
t_m = t_f - t_i

print(t_m)

[[14 21 10 11 21 18 13 22 18  9 28 17 16  8 22]
 [21 12 20 17 13 18 11 16 18 15 31 19 12  9 22]
 [10 20  8  7 17 14 10 13 17  4 17 12 17  6 13]
 [11 17  7  6 15 11  9 12 18  6 22 12 10  6 11]
 [21 13 17 15 10 11 10 13 20 10 27 18 11 12 15]
 [18 18 14 11 11  8  9 13 13  5 15 20 17  9 13]
 [13 11 10  9 10  9 10 17 13 12 24 19  9 11 13]
 [22 16 13 12 13 13 17 18 23 10 31 23 14 10 21]
 [18 18 17 18 20 13 13 23 14  8 21 24 22 11 24]
 [ 9 15  4  6 10  5 12 10  8  2  9 10 15 10  9]
 [28 31 17 22 27 15 24 31 21  9 30 32 31 20 31]
 [17 19 12 12 18 20 19 23 24 10 32 20 20 10 25]
 [16 12 17 10 11 17  9 14 22 15 31 20 10  7 15]
 [ 8  9  6  6 12  9 11 10 11 10 20 10  7  6 11]
 [22 22 13 11 15 13 13 21 24  9 31 25 15 11 18]]
0.0019054412841796875


#Pruebas con C 

In [17]:
# variable de tipo String que en si es el programa
codigo = """
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
const int N = 3;

void foo_function(int arr[N][N]){
    int i, j;
    for (i = 0; i < N; i++)
      for (j = 0; j < N; j++)
        arr[i][j] = 0;
    	printf("%d \t", arr[i][j]);
}
*/

int main(int argc, char const *argv[]){
	int n = 3000;
	int D[n][n];
	float p = 0.8;
	int i,j;
	int **A;
	//foo_function(matrix_a);
	
	//Aquí generamos la matriz
	for (i = 0; i < n; i++){
		for(j= 0 ; j < n; j++){
			D[i][j] = 0;
		}
	}

	for (i = 0; i < n; i++){
		for(j= i +1 ; j < n; j++){
			double r = ((double) rand() / (RAND_MAX));
			printf(" %f \n ", r);
			if ( r < p){
					D[i][j] = 1;
					D[j][i] = 1;
			}
		}
	}

	//Hasta aquí tenemos la matriz de adyacencia


	//Esto es para imprimir la matriz
	/*
	for (i = 0; i < n; i++){
		for(j= 0; j < n; j++){
			printf(%d \t", D[i][j]);
		}
		printf("------------ \n");
	}
	*/


	//#Primer algoritmo secuencial.
	int number_triagles[n];
	int number_degree[n];
	float clustering[n];

	//Sacamos el vector de grados
	for (int node = 0; node < n; ++node){
		int degree = 0;
		for (int k = 0; k < n; ++k){
			degree += D[node][k];
		}
		number_degree[node] = degree;
		//printf("Node %d ------> %d \n",node, degree );
	}

	//Sacamos los triángulos
	for (int node = 0; node < n; ++node){
		//printf("%ls\n", D[node]);
		number_triagles[node] = 0;
		for (int v = 0; v < n; ++v){
			int v_comun_v = 0;
			if ( node != v){
				//printf("%d , %d \n", node, v );
				//Conteo de triángulos
				if (D[node][v] == 1){
					for (int k = 0; k < n; ++k){
						v_comun_v += D[node][k] * D[v][k];
					}
				}
			
			}
			//Este es el doble de números al cuadrado
			number_triagles[node] += v_comun_v;
		}
		//typeof(D[node][node]);
		//printf("%d  --------- %d \n", node+1, number_triagles[node]);
	}

	//Sacamos clustering
	for (int node = 0; node < n; ++node){
		float t = (float) number_triagles[node];
		float d = (float) number_degree[node];
		//printf("%f \n", t / (d * (d-1)) );
	}
	//Acaterminaclustering
	
}
"""

In [18]:
# se crea el archivo con permisos para escribir mediante python
archivo_texto = open("hola.c", "w")
# se escribe el programa en el archivo 
archivo_texto.write(codigo)
# se cierra el buffer de escritura
archivo_texto.close()

In [43]:
!gcc -o foo foo.c

In [ ]:
!cat foo.c

In [47]:
!./foo